// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace OneSim.Traffic.Persistence.Migrations.HistoricalDb
{
    [DbContext(typeof(OneSim.Traffic.Persistence.HistoricalDbContext))]
    [Migration("20191229071239_TerminologyUpdate")]
    partial class TerminologyUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OneSim.Traffic.Domain.Entities.TrafficDataArchiveEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("FetchTime")
                        .HasColumnType("interval");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("TrafficData")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrafficData");
                });
#pragma warning restore 612, 618
        }
    }
}
