// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneSim.Map.Persistence;

namespace OneSim.Map.Persistence.Migrations.HistoricalDbContext
{
    [DbContext(typeof(Persistence.HistoricalDbContext))]
    partial class HistoricalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OneSim.Map.Domain.Entities.StatusFileArchiveEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("DownloadTime")
                        .HasColumnType("interval");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("StatusFile")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
